#!/usr/bin/env bash
# redirect with 404

sudo apt-get update
sudo apt-get -y install nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/haroldo.tech
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
cd /etc/nginx/sites-available
sudo sed -i "s/server_name _;/$new_string/" default
new_string="49i \\\terror_page 404 /custom_404.html;\n\tlocation /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "$new_string" /etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/custom_404.html > /tmp/tmp.txt
sudo service nginx start
