#!/usr/bin/env bash
# conf HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen webapp 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 1267-web-01 34.228.14.173:80 check\n\tserver 1267-web-02 35.231.202.218:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
