#!/usr/bin/env bash
# Display Holberton School ten times

x="holbertonschool"
if [ -e "$x" ]; then
    echo "$x file exists"
    if [ -s "$x" ]; then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$x" ]; then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
